num1 = int(input("enter first number: "))
num2 = int(input("enter second number"))
num3 = int(input("enter third number"))
num4 = int(input("enter fourth number"))


print(num1 + num2)
print(num4 + num1)
print(num3 + num2)
print(num2 + num4)
print(num1 + num2)
print(num1 * num2)
print(num4 * num2)
print(num1 * num2)
print(num3 * num2)
print(num1 * num2)
print(num1 - num3)
print(num1 - num2)
print(num1 - num2)
print(num1 - num4)
print(num2 // num2)
print(num1 // num2)
print(num3 // num2)
print(num1 // num2)
print(num1 // num2)
print(num1 ** num2)
print(num3 ** num2)
print(num1 ** num2)
print(num4 ** num2)
print(num1 ** num2)
print(num1 ** num2)
print(num1 ** num2)
print(num4 ** num2)